app/views/auth_views.py
from flask import (
    Blueprint,
    render_template,
    request,
    url_for,
    flash,
    session,
    g,
    abort,
)
from uuid import uuid4
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import redirect
from sqlalchemy import func

from app import db
from app.forms import (
    UserCreateForm,
    UserSigninForm,
    ChangePwForm,
    SearchPwForm,
    ResetPwForm,
    LeaveForm,
)
from app.models import User, Cook, Collect, ResetPw

from tasks import mail_send


bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    if g.user:
        # 이미 로그인된 경우 404 return
        abort(404)

    form = UserCreateForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user:
            # 유저 정보 생성
            user = User(email=form.email.data,
                        password=generate_password_hash(form.password1.data),
                        name=form.server.data + '@' + form.name.data,
                        )
            db.session.add(user)

            # 유저의 collect 정보 init
            cook_list = Cook.query.all()
            for cook in cook_list:
                collect = Collect(user=user.id, cook=cook.id)
                db.session.add(collect)

            # 데이터베이스 커밋
            db.session.commit()

            # 회원가입이 완료되면 로그인 페이지로 redirect
            return redirect(url_for('auth.signin'))
        else:
            flash('이미 존재하는 email ID입니다.')

    return render_template('auth/signup.html', form=form)

@bp.route('/signin/', methods=('GET', 'POST'))
def signin():
    if g.user:
        # 이미 로그인 된 경우 404 return
        abort(404)

    form = UserSigninForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if not user or not check_password_hash(user.password, form.password.data):
            error = "아이디 혹은 비밀번호가 올바르지 않습니다."
            flash(error)
        else:
            session.clear()
            session['user_id'] = user.id

            next = request.form.get("next")
            if next:
                return redirect(next)
            return redirect(url_for('main.main'))

    return render_template('auth/signin.html', form=form)

@bp.route('/signout/', methods=('GET',))
def signout():
    session.clear()

    return redirect(url_for('main.main'))

@bp.route('/change_pw/', methods=('GET', 'POST'))
def change_pw():
    if g.user == None:
        # 로그인되지 않은 상태에는 비밀번호 변경 불가능
        # abort(404)
        return redirect(url_for('auth.signin'))

    form = ChangePwForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = g.user

        if check_password_hash(user.password, form.old_pw.data) is False:
            error = "현재 비밀번호가 올바르지 않습니다."
            flash(error)
        else:
            user.password = generate_password_hash(form.new_pw1.data)
            db.session.commit()
            return redirect(url_for('main.main'))

    return render_template('auth/changepw.html', form=form)

@bp.route('/search_pw/', methods=('GET', 'POST'))
def search_pw():
    if g.user:
        return abort(404)

    form = SearchPwForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        uuid = str(uuid4())

        duplicate = ResetPw.query.filter_by(addr=uuid).first()
        while duplicate is not None:
            uuid = str(uuid4())
            duplicate = ResetPw.query.filter_by(addr=uuid).first()

        page = ResetPw(
            user=user.id,
            addr=uuid,
        )
        db.session.add(page)
        db.session.commit()

        origin_url = request.url_root

        mail_send.delay(user.email, origin_url, uuid)

        return render_template('auth/sending_email.html')

    return render_template('auth/searchpw.html', form=form)

@bp.route('/reset_pw/<uuid>/', methods=('GET', 'POST'))
def reset_pw(uuid):
    # 비밀번호 찾기 로직을 통해 받은 이메일 링크를 통해 비밀번호 변경
    page = ResetPw.query.filter_by(addr=uuid).first()
    if page is None or page.is_expired == True:
        return abort(404)

    form = ResetPwForm()

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.get(page.user)
        user.password = generate_password_hash(form.new_pw1.data)

        # 한 번 비밀번호 변경에 사용된 페이지는 바로 expired
        page.is_expired = True

        db.session.commit()
        return render_template('auth/complete_resetpw.html')

    return render_template('auth/resetpw.html', form=form)

@bp.route('/leave/', methods=('GET', 'POST'))
def leave():
    if g.user == None:
        # 로그인하지 않은 채로 회원탈퇴 불가능
        abort(404)

    form = LeaveForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = g.user

        if not check_password_hash(user.password, form.password.data):
            error = "비밀번호가 올바르지 않습니다."
            flash(error)
        else:
            db.session.delete(user)
            db.session.commit()

            # 로그아웃을 위해 session을 비운 후, g 객체의 유저 정보를 지움
            session.clear()
            g.user = None

            return render_template('auth/after_leave.html')

    return render_template('auth/leave.html', form=form)

@bp.route('/info/', methods=('GET',))
def info():
    if g.user == None:
        abort(404)

    collects = Collect.query.with_entities(Collect.state, func.count(Collect.state)).group_by(Collect.state).all()

    state_count = {0: 0, 1: 0, 2: 0}
    for co in collects:
        state_count[co[0]] = co[1]

    return render_template('auth/info.html', count=state_count)

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

app/views/book_views.py
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    g,
    flash,
    request,
    Response,
    make_response,
)
from sqlalchemy import or_

from app import db
from app.models import Cook, User, Collect
from app.enums import Method

bp = Blueprint('book', __name__, url_prefix='/book')


@bp.route('/', methods=('GET',))
def main():
    if g.user == None:
        # 로그인 해야지만 도감 페이지에 접근 가능
        flash("도감 페이지를 이용하기 위해서는 로그인이 필요합니다.")
        return redirect(url_for('auth.signin', next=request.url))

    query = request.args.get('q', type=str, default='')
    range = request.args.get('r', type=str, default='all')
    method = request.args.get('m', type=str, default='')
    collected = request.args.get('c', type=str, default='')

    # Cook 모델과 Collect join 및 user 필터링
    join_query = db.session.query(Cook, Collect).join(Collect, Collect.cook == Cook.id)\
        .filter(Collect.user == g.user.id)

    # Cook 모델 필터링
    if query:
        if range == 'name':
            join_query = join_query.filter(Cook.name.like(f'%{query}%'))
        elif range == 'ingredients':
            join_query = join_query.filter(Cook.ingredients.like(f'%{query}%'))
        else:
            join_query = join_query.filter(or_(Cook.name.like(f'%{query}%'), Cook.ingredients.like(f'%{query}%')))

    if method:
        method_list = method.rstrip().split(" ")
        join_query = join_query.filter(Cook.method.in_(method_list))

    # Collect 모델 필터링
    if collected:
        collected_list = collected.rstrip().split(" ")
        join_query = join_query.filter(Collect.state.in_(collected_list))

    join_list = join_query.all()
    method_list = list(Method)

    resp = make_response(render_template('book/book.html', join_list=join_list,
                                         method_list=method_list, query=query, range=range))
    resp.set_cookie('range', range)
    # resp.set_cookie('method', method)
    # resp.set_cookie('collected', collected)

    return resp


@bp.route('/change_state/', methods=('POST',))
def change_state():
    user_id = User.query.get_or_404(g.user.id).id
    data = request.get_json()

    collect = Collect.query.get_or_404({"user": user_id, "cook": data['cook_id']})
    collect.state = data['new_state']
    db.session.commit()

    return Response('', status=200)

app/views/main_views.py
from flask import (
    Blueprint,
    render_template,
)

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def main():
    return render_template('main.html')

app/templates/form_errors.html
{# 필드 오류 #}
{% for field, error in form.errors.items() %}
    <div class="alert alert-danger" role="alert">
        <strong>{{ form[field].label }}</strong>: {{ ', '.join(error) }}
    </div>
{% endfor %}

{# flash 오류 #}
{# flash('') < 해당 코드로 생성되는 오류 #}
{% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
{% endfor %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>마비노기 요리 도감</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="icon" href="/static/image/favicon.ico">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    {% include 'nav.html' %}
    <main role="main">
        {% block content %}
        {% endblock %}
    </main>

    <script src="/static/js/jquery-3.6.0.min.js"></script>
    <script src="/static/js/jquery.validate.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

app/templates/main.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container center" style="font-family: mabi">
        <h1>마비노기 요리 도감 사이트</h1>
    </div>
{% endblock %}

app/templates/nav.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top border-bottom" style="font-family: mabi">
    <a class="navbar-brand font-weight-bold" href="{{ url_for('main.main') }}">마비노기 요리 도감</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarContent"
            aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('book.main') }}">도감</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto justify-content-end">
            {% if g.user == None %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signin') }}">로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">회원가입</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('auth.info') }}">{{ g.user.name }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.signout') }}">로그아웃</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

app/templates/page_not_found.html
{% extends 'layout.html' %}

{% block content %}
    <h1>404 NOT FOUND</h1>
    <button class="btn btn-danger mt-3" onclick="history.back()">이전 페이지로 돌아가기</button>
{% endblock %}